language: java

script: ./.travis-build.sh

sudo: false

jdk:
  - oraclejdk8
#  - oraclejdk7
  - openjdk7

notifications:
  email:
    - annotation-tools-dev@googlegroups.com

after_success:
  - curl -LO https://raw.github.com/mernst/plume-lib/master/bin/trigger-travis.sh
  - sh trigger-travis.sh typetools checker-framework $TRAVISTOKEN "Triggered by upstream build of typetools/annotation-tools"
