language: java

script: ./.travis-build.sh

sudo: false

jdk:
  - oraclejdk8
#  - oraclejdk7
  - openjdk7

notifications:
  email:
    - annotation-tools-dev@googlegroups.com

after_success:
  - curl -s https://raw.githubusercontent.com/mernst/plume-lib/master/bin/trigger-travis.sh > trigger-travis.sh  
  - bash trigger-travis.sh typetools checker-framework $TRAVISTOKEN
